[env]
KUBECONFIG = "{{config_root}}/kubeconfig"
JUST_UNSTABLE = "1"
LEFTHOOK_OUTPUT = "false"

[tools]
"pipx:flux-local" = "latest"
"ansible" = "latest"
helmfile = "latest"
helm = "latest"
1password-cli = "latest"
"aqua:cilium/cilium-cli" = "0.19.0"
"aqua:cli/cli" = "2.83.2"
"aqua:cloudflare/cloudflared" = "2026.1.1"
"aqua:jqlang/jq" = "1.8.1"
"aqua:mikefarah/yq" = "4.50.1"
