[env]
KUBECONFIG = "{{config_root}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
JUST_UNSTABLE = "1"
LEFTHOOK_OUTPUT = "false"

_.file = [
  "{{config_root}}/.secrets.env",
]

[tools]
"pipx:flux-local" = "latest"
"ansible" = "latest"
helmfile = "latest"
gum = "latest"
helm = "latest"
"aqua:cilium/cilium-cli" = "0.19.0"
"aqua:cli/cli" = "2.83.2"
"aqua:cloudflare/cloudflared" = "2026.1.1"
"aqua:jqlang/jq" = "1.8.1"
"aqua:mikefarah/yq" = "4.50.1"