[env]
KUBECONFIG = "{{config_root}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
JUST_UNSTABLE = "1"
LEFTHOOK_OUTPUT = "false"

_.file = [
  "{{config_root}}/.secrets.env",
]

[tools]
"pipx:flux-local" = "latest"
"ansible" = "latest"
helmfile = "latest"
gum = "latest"
