apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:vj3LxWDrfLveL4+K4tcPBar9Iivcp31ygzPxUjWFnE+sDaaWFumeVA==,iv:jTdBEVwegHUJrpBfwQY9aMeJA5YqE65N1Cb0QUVSYPc=,tag:6mePLSFr+S/lfYDn85hnrA==,type:str]
sops:
  age:
    - recipient: age1yya2fd0zxkaephln4ajqfm4645afx8t3ph2qm860gs8uwaq8zumsy45gm5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUUhCZ3E2Q1ZUbFA0ZXFS
        UVJRWDBBRytndTZaY2RMdFRUMyswRzNYVzJZCm9naWhDZXNjNFdJa1BDMkNrRy9x
        RHhJcTlLUTlOdE5wNjV4eUNGS3JUb3cKLS0tIEtQbFdWOGNFQk5UcjUxYnlIdjJQ
        biticVV5NGlaWThoNEtFci95M0laNm8KjcZnbwHRt2gHxR0lorcDSx5ym4/kO98P
        r9i2t0r/r+UT/uEUg1v50gN91UmyUpfnSgsOrsHdjT2BgDz/1Trnmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T05:05:34Z"
  mac: ENC[AES256_GCM,data:rNZ71Ib0eVOU2Z08EgbCG2rO3lbV3TVkep37WbXJnR2ZcXhuxZPybGgNbLGqsAoTGih9+V8Wtn+rsIFtElV3+Wz92j2YGvrCLjAoqsGvqr6NF2dilss4P1oA5MJGzW/5h1RPAnk4Lg7HEoQ9untlatm6vHJ8ni+tNSDTj/MOB9o=,iv:VNuK/ChDN25uYJdZNDUSOk9Htbnsf6dbLMgXi/i/Uek=,tag:2D1D+UDs6XvMpar7SnOuvA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
