apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:knRxbleNv8T7ljLyqIWxYn5vfGgAlaqg0ZKLX/GYpiTIvSjNEgvByQ==,iv:j74SrIaoqYeAbliFO4TNAez6QBiZNLXTIkgQJFJdwPI=,tag:HVtg7tR0he4olBjoyg6XxA==,type:str]
sops:
  age:
    - recipient: age1yya2fd0zxkaephln4ajqfm4645afx8t3ph2qm860gs8uwaq8zumsy45gm5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlamUzWW9DTHE1RkJLZkl2
        cXc1V1Y0YnZWUCtDSThVb1ZVQzlhRjQzaXdRCmdRVHRVNktnenE3U0VEZnJEZGdB
        ZG1NMEN1VEFoeHptSEZuVy9PRThpZVkKLS0tIFdpZ0hnbWE2UlgraE1YN2ZUdVNh
        T2NqbHRZTHJtUEp0aitUZ2xmbENBbncKGHajypTqSq+lUmaHZluKJWqRWHpKVD/l
        vn2b2BmyBUKpn+DRCqVzBNcRN+siaTdOGoGQ4rSKXdnXsJ5kzCmmqg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T05:22:54Z"
  mac: ENC[AES256_GCM,data:VGnkXi6GiOi28vNrZRCwzAavKHpk32QFpTowQcqcnM+2vRfVS13L6o52F4V9ZysHbjJ5xDtbkjancIsywOR7lYNRNZyv/ckJJ7pG828G9aD/mpN/gTO8WfCKdkgDqbks/EYiavl+dQBZSvvwkYJuVZ0ngieeHjKQS7qPH7OEBxs=,iv:krDOzRqx/k/QyWIs2eLM+1TtBz0pLOq1QMVy2lJtdEU=,tag:OUianWiGydUREVTIougYVw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
