apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:S97gK1kISu4w+H21mpuZEIg5SqESfAnZBCQrup3ohvUcX/k4x6M9oQ==,iv:rxc5GLQNgp6ap8IgWYhwNlCMzW18O/zuAipWAU4cg8I=,tag:bp37dAAnaG/wt6/7vdJ0kA==,type:str]
sops:
  age:
    - recipient: age1yya2fd0zxkaephln4ajqfm4645afx8t3ph2qm860gs8uwaq8zumsy45gm5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuT0xBYmVTUTNNQS9PKy8z
        UXpVVkorQ2pxUGJ2cUJXcGFzM01QOEswTEJrCmFiNGExczRHMEZCN2UrNG5NTWts
        WFNRVzhFTnk2Z2RIMFhLdk1mSUlGdzgKLS0tIFEweUx1bmpDcVZCcWFleTRiS1cx
        MGVxMWFtNFRkNVNZTVBNQ3ljV0NoM1EKS7iyWMYaS81JQNRIhiOL7MdZB45iTErG
        Adx/ihnpYoe26goLnzUbDiMv5Iw2pC16HLPP7p8JAIjf5l8TquQXLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T05:51:19Z"
  mac: ENC[AES256_GCM,data:5iD8haq5Pxb/3sPBicQxRujV91nSEhaXP7qbuQoaSiKtRbynZEJqE6AQeKR9aFk/N+v+ut0Gi9eUhELa2ypcfZsyeHZtGZOz7arootjPm5EzqRroi/IQKGYEF5Dq073+AafK+3KBPE0zrQo2vfHOc0PlCeVgr9RF4sfPfJOMw0U=,iv:j6xXvQCs6/aQZ/FepMI8lAZmbkanQOm1qcjX29MW8Yk=,tag:rRPQr5V0fnXhkT56GqZg7g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
