apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:M9pATFyXVjUs/YBbGMJNDI6kOPNCmAa34QI5os1WUPHjSMkJszpQNA==,iv:epv0czyBHdZJKjybARbQ3vGKREsNimC+gijvvZv/mtk=,tag:H907r/pgtjL/LUWfCzyTiA==,type:str]
sops:
  age:
    - recipient: age1yya2fd0zxkaephln4ajqfm4645afx8t3ph2qm860gs8uwaq8zumsy45gm5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aW93Ukd1YmdxOExQay92
        OG5wSnJjVkVkV0src0IyUEt2OHZQeERydUVVCllnOGZqdzJqaG1WUUhzeE82d1Ju
        RG5ReVlCRXBMQVFVQ01qTVN4TWVyR28KLS0tIFJ5VVNkZG11RjhmS3VxWFM4OThI
        NFVUZDhSYUVJbTVHNDNmMkdUbTFtejAKeU7XXyqFYZwxgpA4t6w7QocaOiulbaYi
        DEgwpCIqpQasemWnktnSpRnIjOEceenG4yw9K9mhj6Sk2BPlzD5BHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T07:07:51Z"
  mac: ENC[AES256_GCM,data:56NmHRl4dUb1Rxkx9RSF0VpwpACAza3rQBfEm0sfm91jIb5+jFmu5o0bKuMsVClCIQwAi73m1sUlGsKiaYXazSgsIIXgmbcaGNmiNasKDvQQLdETQU/vHvvzs0Py1QLcJNVFgMCAj/Tks2dVFcgUvq60ycQdaKiU2xJU2L4iQm8=,iv:Won2jLxaKPs2UkRO84iAndQ0H9f5sz28y0puu1vLQBI=,tag:jHVypi3DGAtQ7SMArlSZbA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
