---
# Common Molecule configuration is located at <project root>/.config/molecule/config.yml
platforms:
  - name: instance-1
    groups:
      - instances
    image: ${MOLECULE_DISTRO:-geerlingguy/docker-ubuntu2404-ansible:latest}
    command: ${MOLECULE_COMMAND:-/usr/sbin/init}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    docker_networks:
      - name: headscale
    networks:
      - name: bridge
      - name: headscale
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: instance-2
    groups:
      - instances
    image: 'ghcr.io/artis3n/docker-amazonlinux2023-ansible:latest'
    command: ${MOLECULE_COMMAND:-/usr/sbin/init}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    docker_networks:
      - name: headscale
    networks:
      - name: bridge
      - name: headscale
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: instance-3
    groups:
      - instances
    image: 'geerlingguy/docker-debian13-ansible:latest'
    command: ${MOLECULE_COMMAND:-/usr/sbin/init}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    docker_networks:
      - name: headscale
    networks:
      - name: bridge
      - name: headscale
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: headscale
    image: ${HEADSCALE_IMAGE:-headscale/headscale:latest}
    command: serve
    pre_build_image: true
    networks:
      - name: headscale
    volumes:
      - "${MOLECULE_PROJECT_DIRECTORY}/molecule/role-machine-default/headscale.config.yaml:/etc/headscale/config.yaml"

provisioner:
  playbooks:
    prepare: ../role-machine-default/prepare.yml
    verify: ../role-machine-default/verify.yml
    cleanup: ../role-machine-default/cleanup.yml

scenario:
  name: role-machine-strategy-free
