apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:jfgDGpI0H0Cv0g==,iv:jV8eEMWTkrHf3RgbTQaJtmakSjNGX0CwBpGtNVOm3Ks=,tag:MJdh/Jw/LovmGg3CejuI6A==,type:str]
sops:
  age:
    - recipient: age1yya2fd0zxkaephln4ajqfm4645afx8t3ph2qm860gs8uwaq8zumsy45gm5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMmw4T1FaWUhWcHYxRDZQ
        WW42akhrZGZFMFNYbGg0T2Qrem1CRks2RUVRCmNzT2syTVM2Tzd3REkybVRrQUFa
        OXQxOFVxbkRDQ1VTNzJ6bTJhV0xyNVEKLS0tIG96bTlUMG9RbWNTeHo4M1VzSm9Q
        Sy9pQ2ZXMjZoWnZyQ2Q0UHZXV0NTTncKGgPvUgnIM/UFjx+XoI/VSO+ND71euAWt
        0pRreKrqoP1b0pDSYmAiow+LuX+xE/EcJjUF2eQmU5Ok5nmwjjkWXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T05:22:54Z"
  mac: ENC[AES256_GCM,data:O/V13Tv/mYqPLW+2I8G4xW6x57OQ7GjUqWCOukvQ6DU2fvzQgWmqG/gl4nmy2NWTZgYEUoPyo9Cvqx1QoQMDmK7sVx6086M6/bRQsobRNqQrXrvWCf4DBKXR7n2nRH3Yv2w4KZT1g9yoCqtYLdNWi8+QPntIh6TslM4aVzsjbJE=,iv:KzKGk74ZsZOYsQsQLtI4KnFteT0rVL9MnSH8KM3FQY8=,tag:wOlvpfJh9bf/oCfgSN0UFA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
