apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:TqTX/QwXSi80MQ==,iv:rWN5oGbArIwUb8XyrnJVNwDqOKQ6hIDRjx8k8rj8Uek=,tag:9QSkfOygBe+8bhFL59r1bw==,type:str]
sops:
  age:
    - recipient: age1yya2fd0zxkaephln4ajqfm4645afx8t3ph2qm860gs8uwaq8zumsy45gm5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlODVMcUNnZkY5dmh5YzBo
        U0NVdjM4Wnl3bUd5WVNUZ1A1VFJLNjBGdlIwCkZQMlI1Z0VWMVBVMFJLVXlBbUIx
        WTBqNzdpMjI1TWVHUW5yUS92ZGg5aFkKLS0tIGRjb25wSFAwbFNOZHFycCs5MnQ5
        UVFpQXlPKzY5elRpdGM5ZGhxRFNFeWMKOv9km16x8WuiKcm2mKaRLNswW4uEKA1k
        cioNUo2OOwDcBmiN87iMslP/GdAXAOHohAayh6p0BM3RxTqhYO2j+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T07:07:51Z"
  mac: ENC[AES256_GCM,data:LfkJYvyZTOJ3J11oD8JvfWSDtbix3T3wKvwWsgFIQ6xF6wzRHxQa9yNfefPWWCoKre2tqXa1CgnwZ0eGpIcLkiS9NMAPfn+5933EvI3xnysZFCoUgjinhGqGgGrcpeBX2wsGzG9Zwnqg5D7pqrVPShwtkI17Z+32x93Yc6i23mQ=,iv:CEOS68xwPYXILfDef4uRNji7oLr8SMUPAsD6Uqp3ufc=,tag:J7Vd3d/tsA0wTKE/a+puvg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
