apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:j7fLLltpCGfnLw==,iv:wWsKxK+ce6tQ4ygvCk2wM5DER6gTt+uru3s4x32MMD4=,tag:5Iq0ERMI4YJjAzNWMwcIFg==,type:str]
sops:
  age:
    - recipient: age1yya2fd0zxkaephln4ajqfm4645afx8t3ph2qm860gs8uwaq8zumsy45gm5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ellIWDJxbldEYzFGZDRi
        V25Gem9iN0VFcnY1TkRNcG9CNnJuaUtJZ1NnCjV0SFJMalZha1FFVHYzbTlnVzlP
        M0FoOFI0QXo3ZEdtSVI2bHF0YnFwd0UKLS0tIDl2QmhONFRjNVJ1b0xGTXl2R0lD
        b2pYZk9lSkdFS0t1eGhtNy9HbWhDMmMKLix1EKYX+n3gWVy6pU+GYFdj5zHYaxjO
        acSYWOsJ6XPdtOf7ZCc9xadUpnE/q06sAqG2vkS7gG6AycrPAaq1cw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T05:05:34Z"
  mac: ENC[AES256_GCM,data:05nGweZ0pMX/7IJF8aRwKmMaZOCA+gC5Wdmks7ml0r5oM67KF/RlP4a6ruZ9PvSrM4O9MoGJROekgvCz6m8UdYg9VFBcyUCpKOienUjibDjWb+SjrEeEUGFZUGnHgy8l2aaNlVIBz5KCLLOcs7rAWMcZJECP75eSTCpPKstsJtY=,iv:ztjtZeGPfV/OSuhlr7iR2WhjjbFYJQniSDYmruzLioA=,tag:CQg2Dy8q+3bn9xP/0GNcFg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
