apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:kmOYcoLCtMb+yQ==,iv:OVt7yfJQXU/OzZKw09ZUbBlzD6H0HECp3B6eMpKPZI8=,tag:is1e+ewUGzNkadmyISSooQ==,type:str]
sops:
  age:
    - recipient: age1yya2fd0zxkaephln4ajqfm4645afx8t3ph2qm860gs8uwaq8zumsy45gm5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVHlWbXh4VjhxNnB2ODll
        QTkvQ2p5R3NQZHcwa2xkREN1Rm1VSGRHMTMwCjJCc1VWQVk4WG05aXlQR2VoL0o3
        bFM1Zmt1VWcvNVdyTDhtV1A1V2F0aHcKLS0tIFRJTEtRQkFOaUhtOUo2Q2JIWW9I
        NUJKY2JtY2xMODdSbU02V0YyOXVBQVkK1E33tIQaXtg3ew6SUD/DTMCxCkm62+ub
        5cISE3UrFuSnVeJCNBOuG73wK0tn7ifNTN43sAyJ/ZWtAaFI0qVO5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T05:51:19Z"
  mac: ENC[AES256_GCM,data:9KvYC18GK3/ZYQtgume3gjcfMHl0Mp99mcBXzQ2w5GZXTzxwYbFltNf7lqLBC5UDRrSW/EiyLBMZOxfcpNXqWMnIIYo9vUYNwMCyXfuMXQpyCgnc2Boad2miBx3eTJTkrPF2TGtsSQWwdrUk/ER7mhJ4lcCwMsOT7Gm/MR5bl7U=,iv:MZS4Idu6o6CBVXh5mxbTesbad9iMutQzHi5zjkdkTlc=,tag:5Hrx7ASAgfHsuSIZTBgI7Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
