apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:YG4n4pClHvY8oTue7Ugjh0MKCy99jExzQCfOrMff32A=,iv:3X70LUmDtIEDbPTOsSeVgVsh5Oy5X5x3mWMTUltoUsc=,tag:9hlxGFQr6Ey8LbMIdc8F9Q==,type:str]
sops:
  age:
    - recipient: age1yya2fd0zxkaephln4ajqfm4645afx8t3ph2qm860gs8uwaq8zumsy45gm5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMytxWk1HS1FiL085OFM2
        MUVSdGlDUWhwbUFzOHpiK3FXaTRvSUhnMHprCmtTZGlVdU1nK3BMaTEycHNtQ2JY
        UXFFVDRtU2dEN05SUkwxWDlGUXNWV0kKLS0tIHg3NzdTZFVKeGM4TXlIODlicHAr
        NmllNjJwYWpYZTJpODE5ZDhEVFdFdE0K3JmelbU5Bb40SVcjrrWcoREDVqv5thIK
        ck0yNVqGHn8xZPCukL91PW2LDHj9AIcs5kFgY/p829mw45Ql1xsF9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T05:05:34Z"
  mac: ENC[AES256_GCM,data:+6Na43CLh6x+8LlJ7c2btjHFfGnDzPIYR0HxWFVfBbwXdCgaA33oEVWVQvI64hczELP9Wf2Vu4h6ysvTx4RSAvXu8+KAFxkDJIr4R3oV/DVxgdiAh59voeGj9nvtdGdBDjl3gfcVap7CuhwhEL7aV+HEqtrET2TUrAilT8xUrY4=,iv:Py5d2HTrHh9vfV1KcVDcKp78rwbwxrFCm3Sh6ihQUhQ=,tag:t+ZfisonbeEjLtQOHGa44A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
