apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:4SAiSrjrXq02S0n1qkLi36+jjEBmT79v5CcHgtSSWWw=,iv:G5nylxD3QGUqjUMc855XamoR+GfVgT+TF7CYWBKF/No=,tag:s5HEA2q67SDHyXyI9xnrNA==,type:str]
sops:
  age:
    - recipient: age1yya2fd0zxkaephln4ajqfm4645afx8t3ph2qm860gs8uwaq8zumsy45gm5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpc0FoNUNtVEl1bkd5VVJS
        c2ZLbHlYS09CcHdDYkhqdGJ2SVpQTGFIb1FZCi9qSHVFdUhzR3o5bmpJVWp5NnFs
        NVl3N2hBMkVJWTJnU0hwMmc4STU2MXcKLS0tIERZZXdHNE94VlVCS2g2ajQySnVL
        U1pKRU5oUkNKTkU0Tmd5RzRmUmNJYW8KbgYxauhFWIOBaoGxWifTy3eA6/RAMl3s
        PR9oNzbnOltxIltivNNVhvj66GHjGtXBP8TYqGxmohPn22aW8PWFTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T05:51:19Z"
  mac: ENC[AES256_GCM,data:tkAt2U88xDf6yKaz7e1z5kCGYF8wHhbpHaoMmxdCPkl/+j+GmH/bygYi+Qh+PXonuVJ2JFor+Pf1qMEp9j1VTCeJRA+f2JgZVX/nSC0mT0dYiyC51/9gdOg43cGQrGu9THA44KO0GHy1ysnMGNmPnLNJ8XgBkA5dU93hxkdgi00=,iv:KTxXBRPo+mV6plFk/EY2d00kr5momrvVRSlhwIyoGoI=,tag:putq7I13sTcfb/r+8HeIwg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
