apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ns9m0nhViHFhRTrtcXMrDHDm76rD9tWa3m4L4thc+gE=,iv:XoyAM9WHTHDZ0nL4Kv67mLdPrgX9EK45GoLT/v8qiAs=,tag:ErRhXwZIoW24+rAIdh64gg==,type:str]
sops:
  age:
    - recipient: age1yya2fd0zxkaephln4ajqfm4645afx8t3ph2qm860gs8uwaq8zumsy45gm5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUalBKV3NZSWp0a1pSQTJo
        bXFjUDFwU2lGWnEyYnV2TE1GZGNVZkNuZmlzCkxaY3ZqVUJUODBaQVh4aVVaTWJ2
        dmpZYVI5ZTVuZlRjYjdVOWpqOHZVSGcKLS0tIEtkRUc3N0lncTVWSXBaV1lzZTVk
        YnVZbElxWW5aemU1WCtpZzNvL2pJYnMKSMVE6013JQXaMFIR+dBD4+p++A4sz1wx
        Vdef2Fq16JEy6fRMevT/33PsiuSpMS6OBD6vu+o6l/R/1MTj6vIoRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T05:22:54Z"
  mac: ENC[AES256_GCM,data:3Xs8bIrXKef9DTp7+0b9uLOknDRWoohvO14sJd0vWA/SmuaWIbSLX2kejqBgi2h/HDyDLPGqHs0KTnC+K+rqeln5YXzabBgVxwP/5f8xVtdObFmw1D/ULjcEdc7IWWiRRMUrvpZYN0xYUgOtjDqoVplK2uSHGUZ45wVvsQh4RRI=,iv:HkAK3nKlwTz9zx2ymEuxBeHIyKZqLPtbKm6mi4rbINQ=,tag:7VLrRexEbeTNJXI2cajqSw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
