apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ervyrZZWsL+LjD36L4Zc/llr4QegTet4yS5j19YRqcg=,iv:89kinjqcsPw6w7cL2SXksboYL0FKbSZlvltFu+nmKsE=,tag:QEazrDRtI0uxf4ClN3oUyA==,type:str]
sops:
  age:
    - recipient: age1yya2fd0zxkaephln4ajqfm4645afx8t3ph2qm860gs8uwaq8zumsy45gm5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUXFkM0s4UEpjY3BMV3JC
        dFFmYjdwS0tTWkQ0VEMxS0VqUU5oQ3dHTndrCnU4SEtQS29qWU1KRzc0alhMN0dF
        NTBpai9aL1dkczVXVWRHMHo1dmJXTncKLS0tIE9xNDdreGlhOHQ5VHJ2YWw3MTd5
        ODZXQ3NIdnpkSEFOYzdKTFlscEs0VUkKhPUB96prnUVGEvoB25oFUEDTy1QMuOeR
        0o4r0tvU7D6PY7A3+JrHHIl3ibgOn1N9LVJCF6BOLal4ziwYygRyrA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T07:07:51Z"
  mac: ENC[AES256_GCM,data:FnFoOV4X34l8T6MpN43FjTRGb+3QoZ6GMceuSwHqweIY1+vurPpZfeQEwXwXPE50Un8ssPWZAaKn8kVOu7lsdG8N2hry4/6mksCLav1Jmt6AXIlo8mWhvXfr9dYAAb1N8aUuDkVGtxu61ULKpWWg7SfSo5L84efAXdO+u0LjVXM=,iv:Ry+WBxXDCqaoLshTZfdxUZ7Ep3BnuSGSzbS5Bmgr/Mo=,tag:Uo/5jvOtSJdCJkHoTK9eRQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
