---
- name: Fedora | Prepare Systemd
  ansible.builtin.import_tasks: ./systemd.yml

- name: Fedora | Remove Tailscale
  become: true
  ansible.builtin.dnf:
    name: "{{ tailscale_package }}"
    state: absent

- name: Fedora | Remove Tailscale Repo
  become: true
  ansible.builtin.file:
    path: /etc/yum.repos.d/tailscale.repo
    state: absent
