apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:h8OMb+nkykMpo/tIHHYYS0VVf8WTNTPXZGQwI4634vtTUxzRbqMHaC5saTMWPKYpmp5aSghNo60z3dhO+4U5G7O+FWJIlahmGDZh6pS6oTlMLd3Z4wZUhCCrEy/59qktFubd0nbKDxYnVKIxrRykiSxyjVd5P5cCQV7txYpV9FXpkgx7SC2QmtfsRyazJj6926H/w26SdeIBjGplARS7tPLwCoLg2fU7XeRK7LrzDiAmtWHe,iv:BaNJBta7QwfVLaCzDZ7jF33OR6pIyw7EmMIqRvlKt48=,tag:3VK2kxMFRzu9yJg/H54SUA==,type:str]
sops:
  age:
    - recipient: age1yya2fd0zxkaephln4ajqfm4645afx8t3ph2qm860gs8uwaq8zumsy45gm5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNDlNYnZoRGxTeU9hT04z
        MG5lWlRBV3l6ZHhBa3pWZ2wzL3lDdGpWZkQ4CnZnNEg2RW9iYXA0aXRzQU54UHEx
        c3ZQM3BsRWZPVGg1T0dTR0Y4bnQwOUkKLS0tIHNyUkJ5eWZvUnRrZTArWVNpaVFV
        QlNEY1VoSTMrT3BQSm1IRllybkF1c1kKRbb3LB1SfivG09bzelW4R4u2F2Uc5Ca6
        cBmBL4bC8909ddFBSOYa6v/1fnSYIx15H3I5dGOZIjDh3CJEX6s/5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T07:07:51Z"
  mac: ENC[AES256_GCM,data:mwMvUvd9TuGhuvnG5F70qG8Qyg7o13uN1iGeqd+21ZzWN2CNt/5l79O1/NNPtpHiIbsFe2ripdWGDWEXEVqc9RBtURWbkRRLcT2DVztjKNPKgTnOP4FlPn9us9EhbAcGCvOSDFsJUpEVDcItRvA2K9vR9ARoiT25Y7F9elS5Dcg=,iv:5SU9e7sU7UpawGVAOopVdUtR3+xSl9/zpVqR7nthkW8=,tag:QDEtxB+GCvcWq2MLMjyajw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
