apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:vk2itdT/4+A8u36I9HvJW6hDkYm4LXKHyrlxHBRNyMuek6DRwZVSBfEDWBFGi8skSr0pC0j25JLmhfirG640yYz8WZJqaB5miGJ2p5/4ZmhXz0wQOEHA2CfdBOEb1EDNuhzddaZ3Qz5jK+NtC83k5XbxnPfTYvkK0f9vARPSJY75/gw7fFwxt8Zg+LJyAu8lzgsj767/MSjA/1nYhNj4ne4Gru0MWVoIrYcsG/lu9p8siAQa,iv:tJY/JHoDRbiAwg8d1fa0rq+UTAiV3TSeHJLdBmXqRnk=,tag:EiLs3F8BairWK8vpqUvyEw==,type:str]
sops:
  age:
    - recipient: age1yya2fd0zxkaephln4ajqfm4645afx8t3ph2qm860gs8uwaq8zumsy45gm5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSURLRGY5a3ZBME9PSStz
        ZS9mcUo5WHV3WDVVc1g2K2pUV0FFWG85RkZVCis2NUVQdmh5bk5teUM3d2d1b3FP
        d1pyejNGdFVhNmF2c1ppSkxOeXJKR3MKLS0tIEY0eUcwaFNaSXNjYVl5dEJZNmxQ
        aXpUNHVnSzViUWJRRWFHUVpXRXROWFEKmNjGcnR4oLaU1ZZD5QIa/NcBJSThmtt5
        +Y9WLIYbCt4ONcpJs8bH/w7oludgIVcXY8Z+XjLpLhpgOR7rKvYWYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T05:05:34Z"
  mac: ENC[AES256_GCM,data:NaHlMXMMpf14UswyxR6PtX/qPYrHI5Ac9r3iCZ4kNrC8q1HEPGlJG0eifOAMRlfpwDDkf4GdaksyA4On6z85pVd7LXvq206DV6vYOk5sNQRBlTEdy6bJSXJDA7DLbNiUpO2UkvY0xm65QhhlsijP8HAUBqIz3lIryE3bVV0QDx8=,iv:O30KmziyE8Mys4Fe80owB5Mkk520c3iiZNoS1r00KCQ=,tag:Nidh03KFmQBIcRqo+nNOAQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
