apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:1+tvaNrMV5har1LCg8Pt53ECpVTtF+DjO9d2IbJTahBNRzbu5gfLju6K48+WBT5hxvAJ3MRKNZ4KO32IQ2dW73rEUZP/2lN59rgOk+UQ+8jNL6dzEWWcP2NqF54B2+/acnm62hALznXRJph+cfmoZBn/5J/jPM8Z86g2MektXGlNLyyzKGxh0/pdyj5zGugv6TVnR6WkiaYfeptI8xCKE5tFl64TH8NZO4eLlSef/FhsFEbG,iv:SNfsEO6HpH1y8Xw6kRg6MIII4N1ttrUURd5MvHuP9OU=,tag:uJaI1Umay2BAvIXCuGopUg==,type:str]
sops:
  age:
    - recipient: age1yya2fd0zxkaephln4ajqfm4645afx8t3ph2qm860gs8uwaq8zumsy45gm5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSjBkQmt2S2tCc0dDQ1Za
        VVNPckVZaDJ1Sld5S1RzYmpzd1BOclNFbjFjClhjQ2N1R0Z4Q09YaTJHSVlCTnYr
        T1F3Mkx3bkJ1RzFrRm5WUXFxKzVLWTAKLS0tIFN0YzhraGRXUUZ4bGFGdGt0NHh5
        ODUzaVZHQ2NSR0o3N3RBekY5bndMbmsKVF3WzISL6079oKYHXDjAyQFflHz6tPh2
        EjncULnRXJw9FlnCqlY6kGo0a4EgNX8CDy5N0OvOO8zRMVvn0PStIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T05:22:54Z"
  mac: ENC[AES256_GCM,data:l0CYlsLpVwlpVqWpVP/J3uyrvXgTxLOehdGO68dS1FrDJoVCqnHsWVJJbHzs0sbi4KAs5TtjrKRoYcigt3ycEVBAsTZr9KSke4ybP0NkGChwSwdhWatyfspuQ+2yMZdejTPvkdt4ikbpi0JKM2Jz0BmEbbq5BNnjJQppHjXo+iA=,iv:H0t/6S8k6uGnVU7aMFuok6wxxVHw4gb6QN0qLAj/bmo=,tag:MKqVZzCsBZkvpYFPMquSxQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
