apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:R0bRzEMjk90xz8hl70KUNKmyQ1c7hEHEU0Ky0iVQUXTtyjcFSW++gvRhy8nz9XlnzV6rwBRUbvA5ke1JpQk3VsU0VScthfD+uTFu4L5Cz0uxA+HIchNqDZbb+e/WDmotNxzganjZDgFJnQHnxOLRvmSM1hQN4CaFMG8IjHu4imFKVnG4lcGW2/DEFQlWv2U8eVbHxSg7EijFIfLd2Mv0nWI2OO0NhDZiiCQF1rwausyTs245,iv:tT52M8Fwj+62XQ81gb/p9CUoFAO9qjCMgVrny34Yx+s=,tag:yDJ44o0QIs0OCEDTMmB+yg==,type:str]
sops:
  age:
    - recipient: age1yya2fd0zxkaephln4ajqfm4645afx8t3ph2qm860gs8uwaq8zumsy45gm5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbitkZzdFNzNQUThyNmRj
        azE5UktqRHcxN2Nsb2pBc3hIcGpBWnBpNEU0CkNJd0t3c3owcjQzNjdEZlhiNm9h
        aW1RLzlmMDkyOWtnTzBScWgzd1lFUncKLS0tIHlwZFJHc0hJUU5IdGQ1eGg1OUpa
        ZmFpSXlpVnhkMkZCSUw5UFAyWGRSaFkKwhm4VgmfB3PX+Z6nVcfLQ0W4V3UeQ43N
        CQl9ilC7XFtxwmRX7zKvQzVvn1zaXuiTkD4ZSG2auV3SQ/9mPVwCGw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T05:51:19Z"
  mac: ENC[AES256_GCM,data:JyMxbl+UN6FVrLdBQiD1WoRxxm+7XKBc29R6whdDqq/Ks+8NQ99LgzutQ/tjqMIUVD6RreVZKUCYjvlThmb++QM/A1RRfbYr99fTEWHMXBwXCvhBgiHvoH/yTo8j4x4DnvuDf13X3hHe1f3GD7/xRhsl1YyPeRkC13b+tfRE72I=,iv:Cd+yZ6XygVjf9SYlfcffPwppYlcjSuzQ6Ypuzro1NWA=,tag:yZxOilAU5PWtyy7cxhBRow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
