apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:KZZVC40GdwJyehlK+tULxrTsdf/xj6uSI0z6awaKK5ARwh/RsLrRcg==,iv:8Z0blE9PUtkueTLZwqfP3eVNmjwo18brwYV4Z2J0uvU=,tag:aQDxrblyS0lbROOGWqaQDw==,type:str]
sops:
  age:
    - recipient: age1yya2fd0zxkaephln4ajqfm4645afx8t3ph2qm860gs8uwaq8zumsy45gm5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRUw1eFRBWWs2eXpIaC83
        cEZ3T2J4WkhxQ2JFdXFrMThhQ01DN3hnV2pFCjFQZS9vRVpXUjlUL29JY3I1NS9R
        b09DeDhvemRPd3RBRkpwK1VTOXEwaUUKLS0tIGxFQU9VaElsVzF4dWE1RS9VbGt5
        VFE5Q0dZNmt1SGVWTlUxYksyM1l1MWMKgT4N3XUqRvlVM4RS84DAdJFbnHGIlfSw
        bAyVr1rdKdqGdgjoJRbFMBlV6gfxOeZqH+5bZWLGQsTXnd1n0G/iiA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T05:51:19Z"
  mac: ENC[AES256_GCM,data:qgOog3VPuzoL8NsESIl1QIzpWNx9ygasocjZv/+fDZUBAkMKZrJtb2YIbcgPBrE0CMRumR5Ix4BGGYTmg1eNeM8t4cDXo2aEFZimoiCvfBspuLCNu6Acuwi89XAmxMjCc0TrGIUZ3hMG4awm7C+EunH/3qWk+hIx99BFPKdnoYk=,iv:1DhmEw25Ok+V4DF3gA0+W+6TofbT6zdcfGhNbgTQAAc=,tag:A0D/uaqldZyVxnH8TM5c2g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
