apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:+8tKjwqxx1FikpwrlAte4qmAKogrHP92omrjR6gzEpce4GKR8LKy9A==,iv:RR9Yyzil4oaaiH/vlaqse0CZpI9KHQ0iJ07alNOjpr8=,tag:f5C7IfZypJCbyzDAVWKJAQ==,type:str]
sops:
  age:
    - recipient: age1yya2fd0zxkaephln4ajqfm4645afx8t3ph2qm860gs8uwaq8zumsy45gm5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDKzhkRkJmbDNCU2FiM0xU
        WktvMGZSSGY5N2s2MjhVY3ZQdkp4OXo0REdnCnNsYXlTaWRUUVptWldjUVVzdnB4
        QnIzc2RTVkdoYWVuRXc4M2tyd3lxYVEKLS0tIGRuSjRlRmVZdnpTQXlzbWlRNEJa
        WHM1a2RGbDFIVFJwK05PRDJCYURaYmcKArIy9crJY9DMM2Ihu8CNzrrwaaDn1lHq
        n+ZCf86cLGlbKceHIcmZI9H8DbnTNNBBqpffwEZc9QBS1IiKixm8dw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T05:22:54Z"
  mac: ENC[AES256_GCM,data:WLtaTRGVlpXYbsoRyxYkEfJiXoqAnp4E/u7i155Hel6ftLciHuNyDWdAGoz+g2exe7d33UuXTxBuSBheOgMHVSCUL9Wi03EpdIlk18hfHJS88V+HXe3oYN7YQNbt1cU6c9bQjCI1ow3yG2Vx70eC1KecmP519LZgzqpOx6cL4GE=,iv:Om0TDI3wAUHvtYZuO47/yLwXPOjiHu0i0eRiyyOXTng=,tag:Vlqp+5PbqibzsxKI/DmsHA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
