apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:DOUJXRpRq5CIViHAPL/YM7V0udIYMKtAlwU4ns71/Oxc/FJZ7RMjYg==,iv:AkFoAsvorJ0+ywBviTKANB2oNugaJHwk6OGcxa/AGxk=,tag:G9esBKESzS4VoS9B7CD39A==,type:str]
sops:
  age:
    - recipient: age1yya2fd0zxkaephln4ajqfm4645afx8t3ph2qm860gs8uwaq8zumsy45gm5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZG41SHFMcDB5ckxseWxp
        Mzl0SFFFd0lGakkybFZLUFZhVlp1eXpNKzJrCjdybXJaUzRjdGdxMytsL25iNjQ1
        dTZoOHJHTTFyYlFaUzlSMk1WNXZCVjgKLS0tIE5mWG9NN1dpMmtweTV3aWVFbnNO
        Mk5KTXBYbU50ZTI0SDZQOVpwbVRLaUEKY+9FRIPRbSxDA1YzdCw9SIgjta3g38V8
        wmNkJ4yQPohvKi8siasHZbWHH3Hy0UOZBhBU3nA58gkFRmiLf4B9fg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T05:05:34Z"
  mac: ENC[AES256_GCM,data:5k5AvGvIt/WpBADsQMrasTb4ee1P/BftNalPWWuwIEQWD68B2THfOJO58dz3oiDCXpsgh0bLms+Wki4ckDS3Br7ATsytaYSGLoUSd2ZIyNIYakOgPS0X2L2HoRkeLC1a/bDeoZXwrlUG7NzsobL+QHNxTrkBPN+/SP2D2QGY5G8=,iv:zcTZSpQc8uuIz5x67KgdlOFPIOFWRmvJE8DJUxlNwG0=,tag:hF91DY7FzYVMhPuulVZ61w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
