---
# Common Molecule configuration is located at <project root>/.config/molecule/config.yml
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-geerlingguy/docker-ubuntu2404-ansible:latest}
    command: ${MOLECULE_COMMAND:-/usr/sbin/init}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

scenario:
  name: role-machine-skip-authentication
