---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: reyaan.dev-production
spec:
  secretName: reyaan.dev-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "reyaan.dev"
  dnsNames: ["reyaan.dev", "*.reyaan.dev"]
