---
- name: Verify
  hosts: instance
  tasks:
    - name: Gather Service Facts
      ansible.builtin.service_facts:

    - name: Get Tailscale path
      ansible.builtin.command: which tailscale
      changed_when: false
      failed_when:
        - tailscale_status.rc != 0
        - tailscale_status.rc != 1
      register: tailscale_status

    - name: Determine state folder
      ansible.builtin.set_fact:
        # Following https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
        tailscale_state_folder: "{{ ansible_facts.env.XDG_STATE_HOME | default(ansible_facts.env.HOME + '/.local/state') }}"

    - name: Get idempotent state directory status
      ansible.builtin.stat:
        path: "{{ tailscale_state_folder }}/artis3n-tailscale"
      register: state_dir

    - name: Assertions
      ansible.builtin.assert:
        that:
          - tailscale_status.rc == 1
          - not state_dir.stat.exists
          - "'tailscaled' not in ansible_facts.services or ansible_facts.services['tailscaled']['status'] == 'stopped'"

    - name: Get tailscale package state file status
      ansible.builtin.stat:
        path: "/var/lib/tailscale/tailscaled.state"
      register: ts_state_dir

    - name: More assertions
      ansible.builtin.assert:
        that:
          - not ts_state_dir.stat.exists
