---
k3s_cluster:
  children:
    server:
      hosts:
        192.168.68.21:
          node_name: k3s-server-01
    agent:
      hosts:
        192.168.68.22:
          node_name: k3s-agent-01
        192.168.68.23:
          node_name: k3s-agent-02

  # Required Vars
  vars:
    ansible_port: 22
    ansible_user: "sysrc"
    k3s_version: "v1.35.0+k3s1"
    token: "!vault |
          $ANSIBLE_VAULT;1.1;AES256
          37663037653965613933306439366433623734336238313435376333376263613633663430366565
          6364326237353166396165633131343461333733383032610a656433316639333564643038616435
          38336262643138663165353865373632613137663636626466646636333237323236383537316562
          6235393862653863630a353638636130333032336362646231313865616435303365386137393063
          62313261393862363864623661316234366262626130333730643163633932663634353330353130
          61303431363232323431626234363238646162376266326536303935636235383661633562363331
          33323731363839626433333936343135306561346638633432313633373439366236656133343133
          66306435646661303239"

    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"

    # Optional vars
    # extra_server_args: ""
    # extra_agent_args: ""
    # extra_install_envs: { 'INSTALL_K3S_SKIP_SELINUX_RPM': 'true' }
    # cluster_context: k3s-ansible
    # api_port: 6443
    # k3s_server_location: /var/lib/rancher/k3s
    # systemd_dir: /etc/systemd/system
    # extra_service_envs: [ 'ENV_VAR1=VALUE1', 'ENV_VAR2=VALUE2' ]
    # user_kubectl: true, by default kubectl is symlinked and configured for use by ansible_user. Set to false to only kubectl via root user.
    kubeconfig: /Users/reyaan/Projects/home-ops/kubeconfig
    # Manifests or Airgap should be either full paths or relative to the playbook directory.
    # List of locally available manifests to apply to the cluster, useful for PVCs or Traefik modifications.
    # extra_manifests: [ '/path/to/manifest1.yaml', '/path/to/manifest2.yaml' ]
    # airgap_dir: /tmp/k3s-airgap-images

    #   These are inner yaml files. Maintain the indentation.
    #   YAML here will be placed as the content of /etc/rancher/k3s/config.yaml
    #   See https://docs.k3s.io/installation/configuration#configuration-file

    server_config_yaml:  |
      flannel-backend: "none"
      disable-network-policy: true
      disable-kube-proxy: true
      embedded-registry: true
      node-taint:
        - "k3s-controlplane=true:NoExecute"
      protect-kernel-defaults: true
      secrets-encryption: true
      disable:
        - metrics-server
        - servicelb
        - traefik
      log: "/var/log/k3s.log"


    #   Same as server_config_yaml, but for the agent nodes.
    #   YAML here will be placed as the content of /etc/rancher/k3s/config.yaml
    #   See https://docs.k3s.io/installation/configuration#configuration-file
    agent_config_yaml:  |
      log: "/var/log/k3s.log"
      protect-kernel-defaults: true

    registries_config_yaml:  |
      mirrors:
        docker.io:
        registry.k8s.io:
